pipeline {
    agent any 
    stages {
        stage('printin headline') {
            steps {
                echo "Dear all, my name is $(whoami) and my hostname is $(hostname)" 
                echo "I am currently in $(pwd) location"
            }
        }
    }
}
