pipeline {
    agent any 
    stages {
        stage('printin headline') {
            steps {
                echo "Dear all" 
                sh "chmod +x ./practice/printdate.sh"
                sh './practice/printdate.sh'
            }
        }
    }
}
